name: CI

on:
  push:
    branches:
      - master

jobs:
  my_testing:
    runs-on: ubuntu-latest
    steps:
      - name: python version
        run: |
          python3 --version
          node -v

      - name: Checkout code
        uses: actions/checkout@v4

      - name: List dir 
        run: ls -la

      - name: run script
        run: python3 app.py
          
      - name: pwd
        run: pwd

      - name: install pylint
        run: apt install pylint

      - name: pylint 
        run: pylint app.py
